# Generated by Django 5.1.3 on 2024-12-29 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linkflower', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.TextField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
