# Generated by Django 5.1.3 on 2024-12-29 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_detection', '0002_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
